# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'A4_Update_actual.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import subprocess



path_ = "memory_bank"

DownloadsFolderPictures = os.listdir(path_)
DownloadsFolderPictures.sort()

for file in DownloadsFolderPictures:
    if file.endswith(".DS_Store"):
        DownloadsFolderPictures.remove(file)

# factor = 820/QtHeight
#ORIGIONAL DIMENTIONS


# new_y_dimention = 900

QtWidth = 1038
QtHeight = 591

#New y length
old_y = 820
new_y = 900
#For x axis and y
factor = old_y/QtHeight



def formula(scalar, new=1,old=1):
    return int(round(scalar +  ((new * scalar)/old)-scalar))

def convert(scalar, factor, y=False, x=False):
    scalar_ = scalar
    if y or x:
        scalar = []
        for j, i in enumerate(scalar_):
            if j == 1 or j == 3: #comment out for x expansion
                scalar.append(formula(i, new = new_y, old = old_y))  
            else:
                scalar.append(i)

    m = []
    for i in range(len(scalar)):
        m.append(int(round(scalar[i]*factor)))

    return m

from pygame import mixer
mixer.init()


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 900)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        Form.setPalette(palette)
        self.label = QtWidgets.QLabel(Form)

        m = convert((0, 0, 1038, 591), factor, y=True)
        self.label.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.label.setGeometry(QtCore.QRect(0, 0, 1038, 591))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("y-6.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.next_3 = QtWidgets.QPushButton(Form)

        m = convert((899, 276, 72, 20), factor, y=True)
        self.next_3.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.next_3.setGeometry(QtCore.QRect(880, 275, 97, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_3.sizePolicy().hasHeightForWidth())
        self.next_3.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.next_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(factor*10)))
        self.next_3.setFont(font)
        self.next_3.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.next_3.setObjectName("next_3")
        self.prev_3 = QtWidgets.QPushButton(Form)
        m = convert((674, 276, 73, 20), factor, y=True)
        self.prev_3.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.prev_3.setGeometry(QtCore.QRect(680, 275, 98, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_3.sizePolicy().hasHeightForWidth())
        self.prev_3.setSizePolicy(sizePolicy)
        self.prev_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.prev_3.setFont(font)
        self.prev_3.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.prev_3.setObjectName("prev_3")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        m = convert((674, 253, 297, 21), factor, y=True)
        self.comboBox_3.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.comboBox_3.setGeometry(QtCore.QRect(680, 248, 297, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.prev_6 = QtWidgets.QPushButton(Form)
        m = convert((674, 538, 73, 20), factor, y=True)
        self.prev_6.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.prev_6.setGeometry(QtCore.QRect(680, 538, 98, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_6.sizePolicy().hasHeightForWidth())
        self.prev_6.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.prev_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.prev_6.setFont(font)
        self.prev_6.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.prev_6.setObjectName("prev_6")
        self.next_6 = QtWidgets.QPushButton(Form)

        m = convert((899, 538, 72, 20), factor, y=True)
        self.next_6.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.next_6.setGeometry(QtCore.QRect(880, 538, 97, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_6.sizePolicy().hasHeightForWidth())
        self.next_6.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.next_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.next_6.setFont(font)
        self.next_6.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.next_6.setObjectName("next_6")
        self.comboBox_6 = QtWidgets.QComboBox(Form)

        m = convert((674, 516, 297, 21), factor, y=True)
        self.comboBox_6.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.comboBox_6.setGeometry(QtCore.QRect(680, 511, 297, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.comboBox_6.setFont(font)
        self.comboBox_6.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.comboBox_6.setObjectName("comboBox_6")
        self.prev_2 = QtWidgets.QPushButton(Form)

        m = convert((375, 276, 73, 20), factor, y=True)
        self.prev_2.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.prev_2.setGeometry(QtCore.QRect(375, 275, 98, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_2.sizePolicy().hasHeightForWidth())
        self.prev_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.prev_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.prev_2.setFont(font)
        self.prev_2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.prev_2.setObjectName("prev_2")
        self.prev_1 = QtWidgets.QPushButton(Form)

        m = convert((76, 276, 73, 20), factor, y=True)
        self.prev_1.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.prev_1.setGeometry(QtCore.QRect(70, 275, 98, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_1.sizePolicy().hasHeightForWidth())
        self.prev_1.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.prev_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.prev_1.setFont(font)
        self.prev_1.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.prev_1.setObjectName("prev_1")
        self.next_2 = QtWidgets.QPushButton(Form)

        m = convert((600, 276, 72, 20), factor, y=True)
        self.next_2.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.next_2.setGeometry(QtCore.QRect(575, 275, 97, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_2.sizePolicy().hasHeightForWidth())
        self.next_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.next_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.next_2.setFont(font)
        self.next_2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.next_2.setObjectName("next_2")
        self.next_1 = QtWidgets.QPushButton(Form)

        m = convert((301, 276, 72, 20), factor, y=True)
        self.next_1.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.next_1.setGeometry(QtCore.QRect(270, 275, 97, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_1.sizePolicy().hasHeightForWidth())
        self.next_1.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.next_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.next_1.setFont(font)
        self.next_1.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.next_1.setObjectName("next_1")
        self.prev_4 = QtWidgets.QPushButton(Form)

        m = convert((76, 538, 73, 20), factor, y=True)
        self.prev_4.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.prev_4.setGeometry(QtCore.QRect(70, 538, 98, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_4.sizePolicy().hasHeightForWidth())
        self.prev_4.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.prev_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.prev_4.setFont(font)
        self.prev_4.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.prev_4.setObjectName("prev_4")
        self.prev_5 = QtWidgets.QPushButton(Form)

        m = convert((375, 538, 73, 20), factor, y=True)
        self.prev_5.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.prev_5.setGeometry(QtCore.QRect(375, 538, 98, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_5.sizePolicy().hasHeightForWidth())
        self.prev_5.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.prev_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.prev_5.setFont(font)
        self.prev_5.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.prev_5.setObjectName("prev_5")
        self.next_5 = QtWidgets.QPushButton(Form)

        m = convert((600, 538, 72, 20), factor, y=True)
        self.next_5.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.next_5.setGeometry(QtCore.QRect(575, 538, 97, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_5.sizePolicy().hasHeightForWidth())
        self.next_5.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.next_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.next_5.setFont(font)
        self.next_5.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.next_5.setObjectName("next_5")
        self.next_4 = QtWidgets.QPushButton(Form)
        m = convert((301, 538, 72, 20), factor, y=True)
        self.next_4.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.next_4.setGeometry(QtCore.QRect(270, 538, 97, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_4.sizePolicy().hasHeightForWidth())
        self.next_4.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.next_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.next_4.setFont(font)
        self.next_4.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.next_4.setObjectName("next_4")
        self.comboBox_5 = QtWidgets.QComboBox(Form)

        m = convert((375, 516, 297, 21), factor, y=True)
        self.comboBox_5.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.comboBox_5.setGeometry(QtCore.QRect(375, 511, 297, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_4 = QtWidgets.QComboBox(Form)

        m = convert((76, 516, 297, 21), factor, y=True)
        self.comboBox_4.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.comboBox_4.setGeometry(QtCore.QRect(70, 511, 297, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_2 = QtWidgets.QComboBox(Form)

        m = convert((375, 253, 297, 21), factor, y=True)
        self.comboBox_2.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.comboBox_2.setGeometry(QtCore.QRect(375, 248, 297, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_1 = QtWidgets.QComboBox(Form)

        m = convert((76, 253, 297, 21), factor, y=True)
        self.comboBox_1.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.comboBox_1.setGeometry(QtCore.QRect(70, 248, 297, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_1.sizePolicy().hasHeightForWidth())
        self.comboBox_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        self.comboBox_1.setFont(font)
        self.comboBox_1.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.comboBox_1.setObjectName("comboBox_1")
        self.label_title = QtWidgets.QLabel(Form)

        m = convert((310, 6, 401, 41), factor, y=True)
        self.label_title.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.label_title.setGeometry(QtCore.QRect(310, 6, 401, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(factor*14)))
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("background-color: transparent;")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_1 = QtWidgets.QLabel(Form)

        m = convert((76, 60, 297, 192), factor, y=True)
        self.label_1.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.label_1.setGeometry(QtCore.QRect(70, 60, 297, 186))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setText("")
        # self.label_1.setPixmap(QtGui.QPixmap("Downloads/AirNotes/IMG_5482.JPG"))
        self.label_1.setScaledContents(True)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Form)

        m = convert((375, 60, 297, 192), factor, y=True)
        self.label_2.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.label_2.setGeometry(QtCore.QRect(375, 60, 297, 186))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        # self.label_2.setPixmap(QtGui.QPixmap("Downloads/AirNotes/IMG_5500.JPG"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)

        m = convert((674, 60, 297, 192), factor, y=True)
        self.label_3.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.label_3.setGeometry(QtCore.QRect(680, 60, 297, 186))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText("")
        # self.label_3.setPixmap(QtGui.QPixmap("Downloads/AirNotes/helical motion.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)

        m = convert((76, 323, 297, 192), factor, y=True)
        self.label_4.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.label_4.setGeometry(QtCore.QRect(70, 323, 297, 186))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setText("")
        # self.label_4.setPixmap(QtGui.QPixmap("Downloads/AirNotes/Screenshot 2022-07-31 at 10.51.07.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)

        m = convert((375, 323, 297, 192), factor, y=True)
        self.label_5.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.label_5.setGeometry(QtCore.QRect(375, 323, 297, 186))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setText("")
        # self.label_5.setPixmap(QtGui.QPixmap("Downloads/AirNotes/IMG_5473.JPG"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)

        m = convert((674, 323, 297, 192), factor, y=True)
        self.label_6.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.label_6.setGeometry(QtCore.QRect(680, 323, 297, 186))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setText("")
        # self.label_6.setPixmap(QtGui.QPixmap("Downloads/AirNotes/IMG_5490.JPG"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalSlider_1 = QtWidgets.QSlider(Form)

        m = convert((69, 299, 301, 25), factor, y=True)
        self.horizontalSlider_1.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.horizontalSlider_1.setGeometry(QtCore.QRect(69, 299, 301, 25))
        self.horizontalSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_1.setObjectName("horizontalSlider_1")
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)

        m = convert((372, 299, 301, 25), factor, y=True)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.horizontalSlider_2.setGeometry(QtCore.QRect(372, 299, 301, 25))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(Form)

        m = convert((676, 299, 301, 25), factor, y=True)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.horizontalSlider_3.setGeometry(QtCore.QRect(676, 299, 301, 25))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_4 = QtWidgets.QSlider(Form)

        m = convert((69, 562, 301, 25), factor, y=True)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.horizontalSlider_4.setGeometry(QtCore.QRect(69, 562, 301, 25))
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.horizontalSlider_5 = QtWidgets.QSlider(Form)

        m = convert((372, 562, 281, 25), factor, y=True)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.horizontalSlider_5.setGeometry(QtCore.QRect(372, 562, 281, 25))
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalSlider_6 = QtWidgets.QSlider(Form)

        m = convert((676, 562, 281, 25), factor, y=True)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.horizontalSlider_6.setGeometry(QtCore.QRect(676, 562, 281, 25))
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.open_1 = QtWidgets.QPushButton(Form)

        m = convert((226, 276, 73, 20), factor, y=True)
        self.open_1.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.open_1.setGeometry(QtCore.QRect(170, 275, 98, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_1.sizePolicy().hasHeightForWidth())
        self.open_1.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.open_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.open_1.setFont(font)
        self.open_1.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.open_1.setObjectName("open_1")
        self.open_2 = QtWidgets.QPushButton(Form)
        m = convert((525, 276, 73, 20), factor, y=True)
        self.open_2.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.open_2.setGeometry(QtCore.QRect(475, 275, 98, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_2.sizePolicy().hasHeightForWidth())
        self.open_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.open_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.open_2.setFont(font)
        self.open_2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.open_2.setObjectName("open_2")
        self.open_3 = QtWidgets.QPushButton(Form)

        m = convert((824, 276, 73, 20), factor, y=True)
        self.open_3.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.open_3.setGeometry(QtCore.QRect(780, 275, 98, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_3.sizePolicy().hasHeightForWidth())
        self.open_3.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.open_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.open_3.setFont(font)
        self.open_3.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.open_3.setObjectName("open_3")
        self.open_6 = QtWidgets.QPushButton(Form)

        m = convert((824, 538, 73, 20), factor, y=True)
        self.open_6.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.open_6.setGeometry(QtCore.QRect(780, 538, 98, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_6.sizePolicy().hasHeightForWidth())
        self.open_6.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.open_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.open_6.setFont(font)
        self.open_6.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.open_6.setObjectName("open_6")
        self.open_5 = QtWidgets.QPushButton(Form)

        m = convert((525, 538, 73, 20), factor, y=True)
        self.open_5.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.open_5.setGeometry(QtCore.QRect(475, 538, 98, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_5.sizePolicy().hasHeightForWidth())
        self.open_5.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.open_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.open_5.setFont(font)
        self.open_5.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.open_5.setObjectName("open_5")
        self.open_4 = QtWidgets.QPushButton(Form)

        m = convert((226, 538, 73, 20), factor, y=True)
        self.open_4.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.open_4.setGeometry(QtCore.QRect(170, 538, 98, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_4.sizePolicy().hasHeightForWidth())
        self.open_4.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        
        self.open_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(10*factor)))
        self.open_4.setFont(font)
        self.open_4.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.open_4.setObjectName("open_4")






        self.print_1 = QtWidgets.QPushButton(Form)
        # self.print_1.setGeometry(QtCore.QRect(151, 276, 73, 20))
        m = convert((151, 276, 73, 20), factor, y=True)
        self.print_1.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.print_1.sizePolicy().hasHeightForWidth())
        self.print_1.setSizePolicy(sizePolicy)
        
        self.print_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(factor*9)))
        self.print_1.setFont(font)
        self.print_1.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.print_1.setObjectName("print_1")
        self.print_2 = QtWidgets.QPushButton(Form)
        # self.print_2.setGeometry(QtCore.QRect(450, 276, 73, 20))
        m = convert((450, 276, 73, 20), factor, y=True)
        self.print_2.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.print_2.sizePolicy().hasHeightForWidth())
        self.print_2.setSizePolicy(sizePolicy)
        
        self.print_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(factor*9)))
        self.print_2.setFont(font)
        self.print_2.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.print_2.setObjectName("print_2")
        self.print_3 = QtWidgets.QPushButton(Form)
        # self.print_3.setGeometry(QtCore.QRect(749, 276, 73, 20))
        m = convert((749, 276, 73, 20), factor, y=True)
        self.print_3.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.print_3.sizePolicy().hasHeightForWidth())
        self.print_3.setSizePolicy(sizePolicy)
        
        self.print_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(factor*(9))))
        self.print_3.setFont(font)
        self.print_3.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.print_3.setObjectName("print_3")
        self.print_4 = QtWidgets.QPushButton(Form)
        # self.print_4.setGeometry(QtCore.QRect(151, 538, 73, 20))
        m = convert((151, 538, 73, 20), factor, y=True)
        self.print_4.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.print_4.sizePolicy().hasHeightForWidth())
        self.print_4.setSizePolicy(sizePolicy)
        
        self.print_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(factor*9)))
        self.print_4.setFont(font)
        self.print_4.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.print_4.setObjectName("print_4")
        self.print_5 = QtWidgets.QPushButton(Form)
        # self.print_5.setGeometry(QtCore.QRect(450, 538, 73, 20))
        m = convert((450, 538, 73, 20), factor, y=True)
        self.print_5.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.print_5.sizePolicy().hasHeightForWidth())
        self.print_5.setSizePolicy(sizePolicy)
        
        self.print_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(factor*9)))
        self.print_5.setFont(font)
        self.print_5.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.print_5.setObjectName("print_5")
        self.print_6 = QtWidgets.QPushButton(Form)
        # self.print_6.setGeometry(QtCore.QRect(749, 538, 73, 20))
        m = convert((749, 538, 73, 20), factor, y=True)
        self.print_6.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.print_6.sizePolicy().hasHeightForWidth())
        self.print_6.setSizePolicy(sizePolicy)
        
        self.print_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(factor*9)))
        self.print_6.setFont(font)
        self.print_6.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.3867, cy:0.392045, radius:0.825346, fx:0.110837, fy:0.125, stop:0.123153 rgba(74, 115, 132, 255), stop:0.817734 rgba(24, 35, 52, 255));\n"
"\n"
"border :1px solid rgb(181, 212, 210);")
        self.print_6.setObjectName("print_6")
        self.label_title_2 = QtWidgets.QLabel(Form)
        m = convert((100, 6, 161, 41), factor, y=True)
        self.label_title_2.setGeometry(QtCore.QRect(m[0], m[1], m[2], m[3]))
        # self.label_title_2.setGeometry(QtCore.QRect(100, 6, 161, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_2.sizePolicy().hasHeightForWidth())
        self.label_title_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(int(round(factor*14)))
        self.label_title_2.setFont(font)
        self.label_title_2.setStyleSheet("background-color: transparent;\ncolor: rgb(135, 207, 95);")
        self.label_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_2.setObjectName("label_title_2")









        # Form.setFixedSize(1440, 900)
        self.comboBox_1.addItems(DownloadsFolderPictures)
        self.comboBox_2.addItems(DownloadsFolderPictures)
        self.comboBox_3.addItems(DownloadsFolderPictures)
        self.comboBox_4.addItems(DownloadsFolderPictures)
        self.comboBox_5.addItems(DownloadsFolderPictures)
        self.comboBox_6.addItems(DownloadsFolderPictures)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.open_1.clicked.connect(self.OpenPhoto_1)
        self.open_2.clicked.connect(self.OpenPhoto_2)
        self.open_3.clicked.connect(self.OpenPhoto_3)
        self.open_4.clicked.connect(self.OpenPhoto_4)
        self.open_5.clicked.connect(self.OpenPhoto_5)
        self.open_6.clicked.connect(self.OpenPhoto_6)

        self.next_1.clicked.connect(self.NextPhoto_1)
        self.next_2.clicked.connect(self.NextPhoto_2)
        self.next_3.clicked.connect(self.NextPhoto_3)
        self.next_4.clicked.connect(self.NextPhoto_4)
        self.next_5.clicked.connect(self.NextPhoto_5)
        self.next_6.clicked.connect(self.NextPhoto_6)

        self.prev_1.clicked.connect(self.PreviousPhoto_1)
        self.prev_2.clicked.connect(self.PreviousPhoto_2)
        self.prev_3.clicked.connect(self.PreviousPhoto_3)
        self.prev_4.clicked.connect(self.PreviousPhoto_4)
        self.prev_5.clicked.connect(self.PreviousPhoto_5)
        self.prev_6.clicked.connect(self.PreviousPhoto_6)

        self.horizontalSlider_1.valueChanged.connect(self.photoScroll_1)
        self.horizontalSlider_2.valueChanged.connect(self.photoScroll_2)
        self.horizontalSlider_3.valueChanged.connect(self.photoScroll_3)
        self.horizontalSlider_4.valueChanged.connect(self.photoScroll_4)
        self.horizontalSlider_5.valueChanged.connect(self.photoScroll_5)
        self.horizontalSlider_6.valueChanged.connect(self.photoScroll_6)

        self.print_1.clicked.connect(self.Print_Picture_1)
        self.print_2.clicked.connect(self.Print_Picture_2)
        self.print_3.clicked.connect(self.Print_Picture_3)
        self.print_4.clicked.connect(self.Print_Picture_4)
        self.print_5.clicked.connect(self.Print_Picture_5)
        self.print_6.clicked.connect(self.Print_Picture_6)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CHANNEL 2"))
        self.next_3.setText(_translate("Form", "NEXT"))
        self.prev_3.setText(_translate("Form", "PREV"))
        self.prev_6.setText(_translate("Form", "PREV"))
        self.next_6.setText(_translate("Form", "NEXT"))
        self.prev_2.setText(_translate("Form", "PREV"))
        self.prev_1.setText(_translate("Form", "PREV"))
        self.next_2.setText(_translate("Form", "NEXT"))
        self.next_1.setText(_translate("Form", "NEXT"))
        self.prev_4.setText(_translate("Form", "PREV"))
        self.prev_5.setText(_translate("Form", "PREV"))
        self.next_5.setText(_translate("Form", "NEXT"))
        self.next_4.setText(_translate("Form", "NEXT"))
        self.label_title.setText(_translate("Form", "CHANNEL 2 A4 NOTES"))
        self.open_1.setText(_translate("Form", "OPEN"))
        self.open_2.setText(_translate("Form", "OPEN"))
        self.open_3.setText(_translate("Form", "OPEN"))
        self.open_6.setText(_translate("Form", "OPEN"))
        self.open_5.setText(_translate("Form", "OPEN"))
        self.open_4.setText(_translate("Form", "OPEN"))
        self.print_1.setText(_translate("Form", "PRINT"))
        self.print_2.setText(_translate("Form", "PRINT"))
        self.print_3.setText(_translate("Form", "PRINT"))
        self.print_4.setText(_translate("Form", "PRINT"))
        self.print_5.setText(_translate("Form", "PRINT"))
        self.print_6.setText(_translate("Form", "PRINT"))
        self.label_title_2.setText(_translate("Form", "VERSION 5"))



    def Print_Picture_1(self):
        path = self.comboBox_1.currentText()
        picture  = f"{path_}/{path}"

        print(picture)
        subprocess.call(["open", picture])

        # # picture = "Picture 8.png"
        # # picture = "z-3.jpg"

        # html_code = f"""
        # <!DOCTYPE html>
        # <html>
        # <head>
        #     <title>Index</title>
        # </head>
        # <body>
        #     <img src="{picture}"/>
        # </body>
        # </html>
        # """
        # with open("index.html", "w") as file:
        #     file.write(html_code)
        #     file.close()


        # webbrowser.open(url, new=0, autoraise=True)


    def Print_Picture_2(self):
        path = self.comboBox_2.currentText()
        picture  = f"{path_}/{path}"

        print(picture)
        subprocess.call(["open", picture])



    def Print_Picture_3(self):
        path = self.comboBox_3.currentText()
        picture  = f"{path_}/{path}"

        print(picture)
        subprocess.call(["open", picture])


    def Print_Picture_4(self):
        path = self.comboBox_4.currentText()
        picture  = f"{path_}/{path}"

        print(picture)
        subprocess.call(["open", picture])

    def Print_Picture_5(self):
        path = self.comboBox_5.currentText()
        picture  = f"{path_}/{path}"

        print(picture)
        subprocess.call(["open", picture])



    def Print_Picture_6(self):
        path = self.comboBox_6.currentText()
        picture  = f"{path_}/{path}"

        print(picture)
        subprocess.call(["open", picture])









    def OpenPhoto_1(self):
        mixer.music.load(f"SoundEffects/Refresh3.mp3")
        mixer.music.play()
        path = self.comboBox_1.currentText()
        self.label_1.setPixmap(QtGui.QPixmap(str(f"{path_}/{path}")))

    def OpenPhoto_2(self):
        mixer.music.load(f"SoundEffects/Refresh3.mp3")
        mixer.music.play()
        path = self.comboBox_2.currentText()
        self.label_2.setPixmap(QtGui.QPixmap(str(f"{path_}/{path}")))

    def OpenPhoto_3(self):
        mixer.music.load(f"SoundEffects/Refresh3.mp3")
        mixer.music.play()
        path = self.comboBox_3.currentText()
        self.label_3.setPixmap(QtGui.QPixmap(str(f"{path_}/{path}")))

    def OpenPhoto_4(self):
        mixer.music.load(f"SoundEffects/Refresh3.mp3")
        mixer.music.play()
        path = self.comboBox_4.currentText()
        self.label_4.setPixmap(QtGui.QPixmap(str(f"{path_}/{path}")))

    def OpenPhoto_5(self):
        mixer.music.load(f"SoundEffects/Refresh3.mp3")
        mixer.music.play()
        path = self.comboBox_5.currentText()
        self.label_5.setPixmap(QtGui.QPixmap(str(f"{path_}/{path}")))

    def OpenPhoto_6(self):
        mixer.music.load(f"SoundEffects/Refresh3.mp3")
        mixer.music.play()
        path = self.comboBox_6.currentText()
        self.label_6.setPixmap(QtGui.QPixmap(str(f"{path_}/{path}")))



    def NextPhoto_1(self):
        mixer.music.load(f"SoundEffects/ButtonPress.mp3")
        mixer.music.play()
        try:
            path = self.comboBox_1.currentText()
            for position, names in enumerate(DownloadsFolderPictures):
                if path == names:
                    image = DownloadsFolderPictures[position+1]
                    break

            pos = self.comboBox_1.currentIndex()
            if pos+2 == self.comboBox_1.count():
                pos = 0
            self.comboBox_1.setCurrentIndex(pos+1)
            self.label_1.setPixmap(QtGui.QPixmap(str(f"{path_}/{image}")))
        except IndexError:
            print("IndexError")


    def NextPhoto_2(self):
        mixer.music.load(f"SoundEffects/ButtonPress.mp3")
        mixer.music.play()
        try:
            path = self.comboBox_2.currentText()
            for position, names in enumerate(DownloadsFolderPictures):
                if path == names:
                    image = DownloadsFolderPictures[position+1]
                    break

            pos = self.comboBox_2.currentIndex()
            if pos+2 == self.comboBox_2.count():
                pos = 0
            self.comboBox_2.setCurrentIndex(pos+1)
            self.label_2.setPixmap(QtGui.QPixmap(str(f"{path_}/{image}")))
        except IndexError:
            print("IndexError")

    def NextPhoto_3(self):
        mixer.music.load(f"SoundEffects/ButtonPress.mp3")
        mixer.music.play()
        try:
            path = self.comboBox_3.currentText()
            for position, names in enumerate(DownloadsFolderPictures):
                if path == names:
                    image = DownloadsFolderPictures[position+1]
                    break

            pos = self.comboBox_3.currentIndex()
            if pos+2 == self.comboBox_3.count():
                pos = 0
            self.comboBox_3.setCurrentIndex(pos+1)
            self.label_3.setPixmap(QtGui.QPixmap(str(f"{path_}/{image}")))
        except IndexError:
            print("IndexError")

    def NextPhoto_4(self):
        mixer.music.load(f"SoundEffects/ButtonPress.mp3")
        mixer.music.play()
        try:
            path = self.comboBox_4.currentText()
            for position, names in enumerate(DownloadsFolderPictures):
                if path == names:
                    image = DownloadsFolderPictures[position+1]
                    break

            pos = self.comboBox_4.currentIndex()
            if pos+2 == self.comboBox_4.count():
                pos = 0
            self.comboBox_4.setCurrentIndex(pos+1)
            self.label_4.setPixmap(QtGui.QPixmap(str(f"{path_}/{image}")))
        except IndexError:
            print("IndexError")

    def NextPhoto_5(self):
        mixer.music.load(f"SoundEffects/ButtonPress.mp3")
        mixer.music.play()
        try:
            path = self.comboBox_5.currentText()
            for position, names in enumerate(DownloadsFolderPictures):
                if path == names:
                    image = DownloadsFolderPictures[position+1]
                    break

            pos = self.comboBox_5.currentIndex()
            if pos+2 == self.comboBox_5.count():
                pos = 0
            self.comboBox_5.setCurrentIndex(pos+1)
            self.label_5.setPixmap(QtGui.QPixmap(str(f"{path_}/{image}")))
        except IndexError:
            print("IndexError")

    def NextPhoto_6(self):
        mixer.music.load(f"SoundEffects/ButtonPress.mp3")
        mixer.music.play()
        try:
            path = self.comboBox_6.currentText()
            for position, names in enumerate(DownloadsFolderPictures):
                if path == names:
                    image = DownloadsFolderPictures[position+1]
                    break

            pos = self.comboBox_6.currentIndex()
            if pos+2 == self.comboBox_6.count():
                pos = 0
            self.comboBox_6.setCurrentIndex(pos+1)
            self.label_6.setPixmap(QtGui.QPixmap(str(f"{path_}/{image}")))
        except IndexError:
            print("IndexError")





    def PreviousPhoto_1(self):
        mixer.music.load(f"SoundEffects/ButtonPress.mp3")
        mixer.music.play()
        try:
            path = self.comboBox_1.currentText()
            for position, names in enumerate(DownloadsFolderPictures):
                if path == names:
                    image = DownloadsFolderPictures[position-1]

                    break

            pos = self.comboBox_1.currentIndex()

            if pos == -1:
                pos = self.comboBox_1.count()
                image = DownloadsFolderPictures[-1]

            self.comboBox_1.setCurrentIndex(pos-1)
            self.label_1.setPixmap(QtGui.QPixmap(str(f"{path_}/{image}")))
        except IndexError:
            print("IndexError")


    def PreviousPhoto_2(self):
        mixer.music.load(f"SoundEffects/ButtonPress.mp3")
        mixer.music.play()
        try:
            path = self.comboBox_2.currentText()
            for position, names in enumerate(DownloadsFolderPictures):
                if path == names:
                    image = DownloadsFolderPictures[position-1]

                    break

            pos = self.comboBox_2.currentIndex()

            if pos == -1:
                pos = self.comboBox_2.count()
                image = DownloadsFolderPictures[-1]

            self.comboBox_2.setCurrentIndex(pos-1)
            self.label_2.setPixmap(QtGui.QPixmap(str(f"{path_}/{image}")))
        except IndexError:
            print("IndexError")


    def PreviousPhoto_3(self):
        mixer.music.load(f"SoundEffects/ButtonPress.mp3")
        mixer.music.play()
        try:
            path = self.comboBox_3.currentText()
            for position, names in enumerate(DownloadsFolderPictures):
                if path == names:
                    image = DownloadsFolderPictures[position-1]
                    break

            pos = self.comboBox_3.currentIndex()
            if pos == -1:
                pos = self.comboBox_3.count()
                image = DownloadsFolderPictures[-1]

            self.comboBox_3.setCurrentIndex(pos-1)
            self.label_3.setPixmap(QtGui.QPixmap(str(f"{path_}/{image}")))
        except IndexError:
            print("IndexError")


    def PreviousPhoto_4(self):
        mixer.music.load(f"SoundEffects/ButtonPress.mp3")
        mixer.music.play()
        try:
            path = self.comboBox_4.currentText()
            for position, names in enumerate(DownloadsFolderPictures):
                if path == names:
                    image = DownloadsFolderPictures[position-1]

                    break

            pos = self.comboBox_4.currentIndex()

            if pos == -1:
                pos = self.comboBox_4.count()
                image = DownloadsFolderPictures[-1]

            self.comboBox_4.setCurrentIndex(pos-1)
            self.label_4.setPixmap(QtGui.QPixmap(str(f"{path_}/{image}")))
        except IndexError:
            print("IndexError")


    def PreviousPhoto_5(self):
        mixer.music.load(f"SoundEffects/ButtonPress.mp3")
        mixer.music.play()
        try:
            path = self.comboBox_5.currentText()
            for position, names in enumerate(DownloadsFolderPictures):
                if path == names:
                    image = DownloadsFolderPictures[position-1]

                    break

            pos = self.comboBox_5.currentIndex()

            if pos == -1:
                pos = self.comboBox_5.count()
                image = DownloadsFolderPictures[-1]

            self.comboBox_5.setCurrentIndex(pos-1)
            self.label_5.setPixmap(QtGui.QPixmap(str(f"{path_}/{image}")))
        except IndexError:
            print("IndexError")


    def PreviousPhoto_6(self):
        mixer.music.load(f"SoundEffects/ButtonPress.mp3")
        mixer.music.play()
        try:
            path = self.comboBox_6.currentText()
            for position, names in enumerate(DownloadsFolderPictures):
                if path == names:
                    image = DownloadsFolderPictures[position-1]

                    break

            pos = self.comboBox_6.currentIndex()

            if pos == -1:
                pos = self.comboBox_6.count()
                image = DownloadsFolderPictures[-1]

            self.comboBox_6.setCurrentIndex(pos-1)
            self.label_6.setPixmap(QtGui.QPixmap(str(f"{path_}/{image}")))
        except IndexError:
            print("IndexError")



    def photoScroll_1(self, value):
        value = value 
        value = round((value/100)*len(DownloadsFolderPictures))
        for position, names in enumerate(DownloadsFolderPictures):
            if position == value:
                self.comboBox_1.setCurrentIndex(value)
                self.label_1.setPixmap(QtGui.QPixmap(str(f"{path_}/{names}")))
                break

    def photoScroll_2(self, value):
        value = value 
        value = round((value/100)*len(DownloadsFolderPictures))
        for position, names in enumerate(DownloadsFolderPictures):
            if position == value:
                self.comboBox_2.setCurrentIndex(value)
                self.label_2.setPixmap(QtGui.QPixmap(str(f"{path_}/{names}")))
                break

    def photoScroll_3(self, value):
        value = value 
        value = round((value/100)*len(DownloadsFolderPictures))
        for position, names in enumerate(DownloadsFolderPictures):
            if position == value:
                self.comboBox_3.setCurrentIndex(value)
                self.label_3.setPixmap(QtGui.QPixmap(str(f"{path_}/{names}")))
                break

    def photoScroll_4(self, value):
        value = value 
        value = round((value/100)*len(DownloadsFolderPictures))
        for position, names in enumerate(DownloadsFolderPictures):
            if position == value:
                self.comboBox_4.setCurrentIndex(value)
                self.label_4.setPixmap(QtGui.QPixmap(str(f"{path_}/{names}")))
                break


    def photoScroll_5(self, value):
        value = value 
        value = round((value/100)*len(DownloadsFolderPictures))
        for position, names in enumerate(DownloadsFolderPictures):
            if position == value:
                self.comboBox_5.setCurrentIndex(value)
                self.label_5.setPixmap(QtGui.QPixmap(str(f"{path_}/{names}")))
                break


    def photoScroll_6(self, value):
        value = value 
        value = round((value/100)*len(DownloadsFolderPictures))
        for position, names in enumerate(DownloadsFolderPictures):
            if position == value:
                self.comboBox_6.setCurrentIndex(value)
                self.label_6.setPixmap(QtGui.QPixmap(str(f"{path_}/{names}")))
                break




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())




        # palette = QtGui.QPalette()
        # brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        # gradient = QtGui.QRadialGradient(0.3867, 0.392045, 0.825346, 0.110837, 0.125)
        # gradient.setSpread(QtGui.QGradient.PadSpread)
        # gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        # gradient.setColorAt(0.123153, QtGui.QColor(74, 115, 132))
        # gradient.setColorAt(0.817734, QtGui.QColor(24, 35, 52))
        # brush = QtGui.QBrush(gradient)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        # brush = QtGui.QBrush(QtGui.QColor(31, 64, 79))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        # brush = QtGui.QBrush(QtGui.QColor(26, 53, 66))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        # brush = QtGui.QBrush(QtGui.QColor(10, 21, 26))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        # brush = QtGui.QBrush(QtGui.QColor(14, 29, 35))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        # brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        # brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        # brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        # gradient = QtGui.QRadialGradient(0.3867, 0.392045, 0.825346, 0.110837, 0.125)
        # gradient.setSpread(QtGui.QGradient.PadSpread)
        # gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        # gradient.setColorAt(0.123153, QtGui.QColor(74, 115, 132))
        # gradient.setColorAt(0.817734, QtGui.QColor(24, 35, 52))
        # brush = QtGui.QBrush(gradient)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        # gradient = QtGui.QRadialGradient(0.3867, 0.392045, 0.825346, 0.110837, 0.125)
        # gradient.setSpread(QtGui.QGradient.PadSpread)
        # gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        # gradient.setColorAt(0.123153, QtGui.QColor(74, 115, 132))
        # gradient.setColorAt(0.817734, QtGui.QColor(24, 35, 52))
        # brush = QtGui.QBrush(gradient)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        # brush = QtGui.QBrush(QtGui.QColor(10, 21, 26))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        # brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        # brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        # brush = QtGui.QBrush(QtGui.QColor(208, 208, 208))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        # gradient = QtGui.QRadialGradient(0.3867, 0.392045, 0.825346, 0.110837, 0.125)
        # gradient.setSpread(QtGui.QGradient.PadSpread)
        # gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        # gradient.setColorAt(0.123153, QtGui.QColor(74, 115, 132))
        # gradient.setColorAt(0.817734, QtGui.QColor(24, 35, 52))
        # brush = QtGui.QBrush(gradient)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        # brush = QtGui.QBrush(QtGui.QColor(55, 55, 55))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        # brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        # brush = QtGui.QBrush(QtGui.QColor(64, 65, 66))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        # brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        # brush = QtGui.QBrush(QtGui.QColor(208, 208, 208))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        # brush = QtGui.QBrush(QtGui.QColor(255, 51, 51))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        # brush = QtGui.QBrush(QtGui.QColor(208, 208, 208))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        # gradient = QtGui.QRadialGradient(0.3867, 0.392045, 0.825346, 0.110837, 0.125)
        # gradient.setSpread(QtGui.QGradient.PadSpread)
        # gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        # gradient.setColorAt(0.123153, QtGui.QColor(74, 115, 132))
        # gradient.setColorAt(0.817734, QtGui.QColor(24, 35, 52))
        # brush = QtGui.QBrush(gradient)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        # gradient = QtGui.QRadialGradient(0.3867, 0.392045, 0.825346, 0.110837, 0.125)
        # gradient.setSpread(QtGui.QGradient.PadSpread)
        # gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        # gradient.setColorAt(0.123153, QtGui.QColor(74, 115, 132))
        # gradient.setColorAt(0.817734, QtGui.QColor(24, 35, 52))
        # brush = QtGui.QBrush(gradient)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        # brush = QtGui.QBrush(QtGui.QColor(53, 54, 55))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        # brush = QtGui.QBrush(QtGui.QColor(64, 65, 66))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        # brush = QtGui.QBrush(QtGui.QColor(208, 208, 208))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        # brush = QtGui.QBrush(QtGui.QColor(10, 21, 26))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        # gradient = QtGui.QRadialGradient(0.3867, 0.392045, 0.825346, 0.110837, 0.125)
        # gradient.setSpread(QtGui.QGradient.PadSpread)
        # gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        # gradient.setColorAt(0.123153, QtGui.QColor(74, 115, 132))
        # gradient.setColorAt(0.817734, QtGui.QColor(24, 35, 52))
        # brush = QtGui.QBrush(gradient)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        # brush = QtGui.QBrush(QtGui.QColor(31, 64, 79))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        # brush = QtGui.QBrush(QtGui.QColor(26, 53, 66))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        # brush = QtGui.QBrush(QtGui.QColor(10, 21, 26))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        # brush = QtGui.QBrush(QtGui.QColor(14, 29, 35))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        # brush = QtGui.QBrush(QtGui.QColor(10, 21, 26))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        # brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        # brush = QtGui.QBrush(QtGui.QColor(10, 21, 26))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        # gradient = QtGui.QRadialGradient(0.3867, 0.392045, 0.825346, 0.110837, 0.125)
        # gradient.setSpread(QtGui.QGradient.PadSpread)
        # gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        # gradient.setColorAt(0.123153, QtGui.QColor(74, 115, 132))
        # gradient.setColorAt(0.817734, QtGui.QColor(24, 35, 52))
        # brush = QtGui.QBrush(gradient)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        # gradient = QtGui.QRadialGradient(0.3867, 0.392045, 0.825346, 0.110837, 0.125)
        # gradient.setSpread(QtGui.QGradient.PadSpread)
        # gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        # gradient.setColorAt(0.123153, QtGui.QColor(74, 115, 132))
        # gradient.setColorAt(0.817734, QtGui.QColor(24, 35, 52))
        # brush = QtGui.QBrush(gradient)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        # brush = QtGui.QBrush(QtGui.QColor(53, 54, 55))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        # brush = QtGui.QBrush(QtGui.QColor(64, 65, 66))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        # brush = QtGui.QBrush(QtGui.QColor(208, 208, 208))
        # brush.setStyle(QtCore.Qt.SolidPattern)
        # palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)